package com.v2grop.lbankpulse;
import android.content.Context;import android.content.SharedPreferences;import android.security.keystore.KeyGenParameterSpec;import android.security.keystore.KeyProperties;import android.util.Base64;
import java.security.KeyStore;import javax.crypto.Cipher;import javax.crypto.KeyGenerator;import javax.crypto.SecretKey;import javax.crypto.spec.GCMParameterSpec;
/** AES-GCM key never leaves Android Keystore. Legacy plaintext removed only after successful encryption. */
public final class SecureTokenStore {
 private static final String ALIAS="vgrop_server_token_v1";
 private static SecretKey key()throws Exception{KeyStore s=KeyStore.getInstance("AndroidKeyStore");s.load(null);if(s.containsAlias(ALIAS))return (SecretKey)s.getKey(ALIAS,null);KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());return g.generateKey();}
 public static void save(Context c,String token)throws Exception{Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,key());String data=Base64.encodeToString(cipher.doFinal(token.getBytes("UTF-8")),Base64.NO_WRAP),iv=Base64.encodeToString(cipher.getIV(),Base64.NO_WRAP);if(!c.getSharedPreferences("secure_token",0).edit().putString("data",data).putString("iv",iv).commit())throw new IllegalStateException("Token persistence failed");c.getSharedPreferences("settings",0).edit().remove("token").commit();}
 public static String read(Context c)throws Exception{SharedPreferences old=c.getSharedPreferences("settings",0),p=c.getSharedPreferences("secure_token",0);if(old.contains("token"))save(c,old.getString("token",""));if(!p.contains("data"))return "";Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Base64.decode(p.getString("iv",""),Base64.NO_WRAP)));return new String(cipher.doFinal(Base64.decode(p.getString("data",""),Base64.NO_WRAP)),"UTF-8");}
}
